- hosts: all
  tasks:
    - name: Install Python
      raw: yum -y install python3
    - name: install apache2
      yum: name=httpd state=present
    - name: httpd is running
      service:
        name: httpd
        state: started
