variable "access_key" { default = "" }
variable "secret_key" { default = ""}
variable "region" { default = "ap-southeast-2" }
variable "vpc_cidr" { default = "10.0.0.0/16" }
variable "public_cidr" { default = "10.0.1.0/24" }
variable "private_cidr" { default = "10.0.2.0/24" }
variable "route_table_cidr" { default = "0.0.0.0/0" }
variable "host" {default = "aws_instance.my_web_instance.public_dns"}
variable "instance_ports" { default = ["22", "80", "443", "3306"] }
variable "availability_zone" { default = "" }
